package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

/**
 * Accounts generated by hbm2java
 */
public class Accounts implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String email;
	private String activationCode;

	public Accounts() {
	}

	public Accounts(String username, String password, String email) {
		this.username = username;
		this.password = password;
		this.email = email;
	}

	public Accounts(String username, String password, String email, String activationCode) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.activationCode = activationCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getActivationCode() {
		return this.activationCode;
	}

	public void setActivationCode(String activationCode) {
		this.activationCode = activationCode;
	}

}
