package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * Tblcargo generated by hbm2java
 */
public class Tblcargo implements java.io.Serializable {

	private Integer tblCargoId;
	private String tblCargoDescricao;
	private int tblCargoUsuario;
	private int tblCargoVersao;
	private Date tblCargoDataCadastro;
	private Date tblCargoDataAlteracao;

	public Tblcargo() {
	}

	public Tblcargo(int tblCargoUsuario, int tblCargoVersao, Date tblCargoDataCadastro, Date tblCargoDataAlteracao) {
		this.tblCargoUsuario = tblCargoUsuario;
		this.tblCargoVersao = tblCargoVersao;
		this.tblCargoDataCadastro = tblCargoDataCadastro;
		this.tblCargoDataAlteracao = tblCargoDataAlteracao;
	}

	public Tblcargo(String tblCargoDescricao, int tblCargoUsuario, int tblCargoVersao, Date tblCargoDataCadastro,
			Date tblCargoDataAlteracao) {
		this.tblCargoDescricao = tblCargoDescricao;
		this.tblCargoUsuario = tblCargoUsuario;
		this.tblCargoVersao = tblCargoVersao;
		this.tblCargoDataCadastro = tblCargoDataCadastro;
		this.tblCargoDataAlteracao = tblCargoDataAlteracao;
	}

	public Integer getTblCargoId() {
		return this.tblCargoId;
	}

	public void setTblCargoId(Integer tblCargoId) {
		this.tblCargoId = tblCargoId;
	}

	public String getTblCargoDescricao() {
		return this.tblCargoDescricao;
	}

	public void setTblCargoDescricao(String tblCargoDescricao) {
		this.tblCargoDescricao = tblCargoDescricao;
	}

	public int getTblCargoUsuario() {
		return this.tblCargoUsuario;
	}

	public void setTblCargoUsuario(int tblCargoUsuario) {
		this.tblCargoUsuario = tblCargoUsuario;
	}

	public int getTblCargoVersao() {
		return this.tblCargoVersao;
	}

	public void setTblCargoVersao(int tblCargoVersao) {
		this.tblCargoVersao = tblCargoVersao;
	}

	public Date getTblCargoDataCadastro() {
		return this.tblCargoDataCadastro;
	}

	public void setTblCargoDataCadastro(Date tblCargoDataCadastro) {
		this.tblCargoDataCadastro = tblCargoDataCadastro;
	}

	public Date getTblCargoDataAlteracao() {
		return this.tblCargoDataAlteracao;
	}

	public void setTblCargoDataAlteracao(Date tblCargoDataAlteracao) {
		this.tblCargoDataAlteracao = tblCargoDataAlteracao;
	}

}
