package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * TblDrivingdistance2s generated by hbm2java
 */
public class TblDrivingdistance2s implements java.io.Serializable {

	private Integer id;
	private String distance;
	private float distancevalue;
	private String time;
	private Integer duracao;
	private String origem;
	private String destino;
	private String segundos;
	private String tm;
	private String url;
	private Date dc;
	private int ativo;

	public TblDrivingdistance2s() {
	}

	public TblDrivingdistance2s(String distance, float distancevalue, String time, String origem, String destino,
			String segundos, String tm, String url, Date dc, int ativo) {
		this.distance = distance;
		this.distancevalue = distancevalue;
		this.time = time;
		this.origem = origem;
		this.destino = destino;
		this.segundos = segundos;
		this.tm = tm;
		this.url = url;
		this.dc = dc;
		this.ativo = ativo;
	}

	public TblDrivingdistance2s(String distance, float distancevalue, String time, Integer duracao, String origem,
			String destino, String segundos, String tm, String url, Date dc, int ativo) {
		this.distance = distance;
		this.distancevalue = distancevalue;
		this.time = time;
		this.duracao = duracao;
		this.origem = origem;
		this.destino = destino;
		this.segundos = segundos;
		this.tm = tm;
		this.url = url;
		this.dc = dc;
		this.ativo = ativo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDistance() {
		return this.distance;
	}

	public void setDistance(String distance) {
		this.distance = distance;
	}

	public float getDistancevalue() {
		return this.distancevalue;
	}

	public void setDistancevalue(float distancevalue) {
		this.distancevalue = distancevalue;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Integer getDuracao() {
		return this.duracao;
	}

	public void setDuracao(Integer duracao) {
		this.duracao = duracao;
	}

	public String getOrigem() {
		return this.origem;
	}

	public void setOrigem(String origem) {
		this.origem = origem;
	}

	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	public String getSegundos() {
		return this.segundos;
	}

	public void setSegundos(String segundos) {
		this.segundos = segundos;
	}

	public String getTm() {
		return this.tm;
	}

	public void setTm(String tm) {
		this.tm = tm;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getDc() {
		return this.dc;
	}

	public void setDc(Date dc) {
		this.dc = dc;
	}

	public int getAtivo() {
		return this.ativo;
	}

	public void setAtivo(int ativo) {
		this.ativo = ativo;
	}

}
