package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * Tbldepartamento generated by hbm2java
 */
public class Tbldepartamento implements java.io.Serializable {

	private Integer tblDepartamentoId;
	private String tblDepartamentoDescricao;
	private int tblDepartamentoVersao;
	private Date tblDepartamentoDataCadastro;
	private Date tblDepartamentoDataAlteracao;

	public Tbldepartamento() {
	}

	public Tbldepartamento(int tblDepartamentoVersao, Date tblDepartamentoDataCadastro,
			Date tblDepartamentoDataAlteracao) {
		this.tblDepartamentoVersao = tblDepartamentoVersao;
		this.tblDepartamentoDataCadastro = tblDepartamentoDataCadastro;
		this.tblDepartamentoDataAlteracao = tblDepartamentoDataAlteracao;
	}

	public Tbldepartamento(String tblDepartamentoDescricao, int tblDepartamentoVersao, Date tblDepartamentoDataCadastro,
			Date tblDepartamentoDataAlteracao) {
		this.tblDepartamentoDescricao = tblDepartamentoDescricao;
		this.tblDepartamentoVersao = tblDepartamentoVersao;
		this.tblDepartamentoDataCadastro = tblDepartamentoDataCadastro;
		this.tblDepartamentoDataAlteracao = tblDepartamentoDataAlteracao;
	}

	public Integer getTblDepartamentoId() {
		return this.tblDepartamentoId;
	}

	public void setTblDepartamentoId(Integer tblDepartamentoId) {
		this.tblDepartamentoId = tblDepartamentoId;
	}

	public String getTblDepartamentoDescricao() {
		return this.tblDepartamentoDescricao;
	}

	public void setTblDepartamentoDescricao(String tblDepartamentoDescricao) {
		this.tblDepartamentoDescricao = tblDepartamentoDescricao;
	}

	public int getTblDepartamentoVersao() {
		return this.tblDepartamentoVersao;
	}

	public void setTblDepartamentoVersao(int tblDepartamentoVersao) {
		this.tblDepartamentoVersao = tblDepartamentoVersao;
	}

	public Date getTblDepartamentoDataCadastro() {
		return this.tblDepartamentoDataCadastro;
	}

	public void setTblDepartamentoDataCadastro(Date tblDepartamentoDataCadastro) {
		this.tblDepartamentoDataCadastro = tblDepartamentoDataCadastro;
	}

	public Date getTblDepartamentoDataAlteracao() {
		return this.tblDepartamentoDataAlteracao;
	}

	public void setTblDepartamentoDataAlteracao(Date tblDepartamentoDataAlteracao) {
		this.tblDepartamentoDataAlteracao = tblDepartamentoDataAlteracao;
	}

}
