package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TblGeocode generated by hbm2java
 */
public class TblGeocode implements java.io.Serializable {

	private Integer id;
	private BigDecimal lati;
	private BigDecimal longi;
	private String formattedAddress;
	private String address;
	private Date datacadastro;

	public TblGeocode() {
	}

	public TblGeocode(BigDecimal lati, BigDecimal longi, String formattedAddress, String address, Date datacadastro) {
		this.lati = lati;
		this.longi = longi;
		this.formattedAddress = formattedAddress;
		this.address = address;
		this.datacadastro = datacadastro;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BigDecimal getLati() {
		return this.lati;
	}

	public void setLati(BigDecimal lati) {
		this.lati = lati;
	}

	public BigDecimal getLongi() {
		return this.longi;
	}

	public void setLongi(BigDecimal longi) {
		this.longi = longi;
	}

	public String getFormattedAddress() {
		return this.formattedAddress;
	}

	public void setFormattedAddress(String formattedAddress) {
		this.formattedAddress = formattedAddress;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getDatacadastro() {
		return this.datacadastro;
	}

	public void setDatacadastro(Date datacadastro) {
		this.datacadastro = datacadastro;
	}

}
