package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * Tblplanilhaendereco generated by hbm2java
 */
public class Tblplanilhaendereco implements java.io.Serializable {

	private Integer tblPlanilhaEnderecoId;
	private String tblPlanilhaEnderecoNome;
	private byte[] tblPlanilhaEnderecoFile;
	private int tblPlanilhaEnderecoVersao;
	private Date tblPlanilhaEnderecoDataCadastro;
	private Integer tblPlanilhaEnderecoUsuarioCadastro;
	private Date tblPlanilhaEnderecoDataAlteracao;
	private Integer tblPlanilhaEnderecoUsuarioAlteracao;

	public Tblplanilhaendereco() {
	}

	public Tblplanilhaendereco(int tblPlanilhaEnderecoVersao, Date tblPlanilhaEnderecoDataCadastro,
			Date tblPlanilhaEnderecoDataAlteracao) {
		this.tblPlanilhaEnderecoVersao = tblPlanilhaEnderecoVersao;
		this.tblPlanilhaEnderecoDataCadastro = tblPlanilhaEnderecoDataCadastro;
		this.tblPlanilhaEnderecoDataAlteracao = tblPlanilhaEnderecoDataAlteracao;
	}

	public Tblplanilhaendereco(String tblPlanilhaEnderecoNome, byte[] tblPlanilhaEnderecoFile,
			int tblPlanilhaEnderecoVersao, Date tblPlanilhaEnderecoDataCadastro,
			Integer tblPlanilhaEnderecoUsuarioCadastro, Date tblPlanilhaEnderecoDataAlteracao,
			Integer tblPlanilhaEnderecoUsuarioAlteracao) {
		this.tblPlanilhaEnderecoNome = tblPlanilhaEnderecoNome;
		this.tblPlanilhaEnderecoFile = tblPlanilhaEnderecoFile;
		this.tblPlanilhaEnderecoVersao = tblPlanilhaEnderecoVersao;
		this.tblPlanilhaEnderecoDataCadastro = tblPlanilhaEnderecoDataCadastro;
		this.tblPlanilhaEnderecoUsuarioCadastro = tblPlanilhaEnderecoUsuarioCadastro;
		this.tblPlanilhaEnderecoDataAlteracao = tblPlanilhaEnderecoDataAlteracao;
		this.tblPlanilhaEnderecoUsuarioAlteracao = tblPlanilhaEnderecoUsuarioAlteracao;
	}

	public Integer getTblPlanilhaEnderecoId() {
		return this.tblPlanilhaEnderecoId;
	}

	public void setTblPlanilhaEnderecoId(Integer tblPlanilhaEnderecoId) {
		this.tblPlanilhaEnderecoId = tblPlanilhaEnderecoId;
	}

	public String getTblPlanilhaEnderecoNome() {
		return this.tblPlanilhaEnderecoNome;
	}

	public void setTblPlanilhaEnderecoNome(String tblPlanilhaEnderecoNome) {
		this.tblPlanilhaEnderecoNome = tblPlanilhaEnderecoNome;
	}

	public byte[] getTblPlanilhaEnderecoFile() {
		return this.tblPlanilhaEnderecoFile;
	}

	public void setTblPlanilhaEnderecoFile(byte[] tblPlanilhaEnderecoFile) {
		this.tblPlanilhaEnderecoFile = tblPlanilhaEnderecoFile;
	}

	public int getTblPlanilhaEnderecoVersao() {
		return this.tblPlanilhaEnderecoVersao;
	}

	public void setTblPlanilhaEnderecoVersao(int tblPlanilhaEnderecoVersao) {
		this.tblPlanilhaEnderecoVersao = tblPlanilhaEnderecoVersao;
	}

	public Date getTblPlanilhaEnderecoDataCadastro() {
		return this.tblPlanilhaEnderecoDataCadastro;
	}

	public void setTblPlanilhaEnderecoDataCadastro(Date tblPlanilhaEnderecoDataCadastro) {
		this.tblPlanilhaEnderecoDataCadastro = tblPlanilhaEnderecoDataCadastro;
	}

	public Integer getTblPlanilhaEnderecoUsuarioCadastro() {
		return this.tblPlanilhaEnderecoUsuarioCadastro;
	}

	public void setTblPlanilhaEnderecoUsuarioCadastro(Integer tblPlanilhaEnderecoUsuarioCadastro) {
		this.tblPlanilhaEnderecoUsuarioCadastro = tblPlanilhaEnderecoUsuarioCadastro;
	}

	public Date getTblPlanilhaEnderecoDataAlteracao() {
		return this.tblPlanilhaEnderecoDataAlteracao;
	}

	public void setTblPlanilhaEnderecoDataAlteracao(Date tblPlanilhaEnderecoDataAlteracao) {
		this.tblPlanilhaEnderecoDataAlteracao = tblPlanilhaEnderecoDataAlteracao;
	}

	public Integer getTblPlanilhaEnderecoUsuarioAlteracao() {
		return this.tblPlanilhaEnderecoUsuarioAlteracao;
	}

	public void setTblPlanilhaEnderecoUsuarioAlteracao(Integer tblPlanilhaEnderecoUsuarioAlteracao) {
		this.tblPlanilhaEnderecoUsuarioAlteracao = tblPlanilhaEnderecoUsuarioAlteracao;
	}

}
