package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * Tblquadrante generated by hbm2java
 */
public class Tblquadrante implements java.io.Serializable {

	private Integer tblQuadranteId;
	private String tblQuadranteNome;
	private String tblQuadrantePoints;
	private String tblQuadranteOrdem;
	private String tblQuadranteDesabilitar;
	private int tblQuadranteVersao;
	private Date tblQuadranteDataCadastro;
	private int tblQuadranteUsuarioCadastro;
	private Date tblQuadranteDataAlteracao;
	private Integer tblQuadranteUsuarioAlteracao;

	public Tblquadrante() {
	}

	public Tblquadrante(String tblQuadranteDesabilitar, int tblQuadranteVersao, Date tblQuadranteDataCadastro,
			int tblQuadranteUsuarioCadastro, Date tblQuadranteDataAlteracao) {
		this.tblQuadranteDesabilitar = tblQuadranteDesabilitar;
		this.tblQuadranteVersao = tblQuadranteVersao;
		this.tblQuadranteDataCadastro = tblQuadranteDataCadastro;
		this.tblQuadranteUsuarioCadastro = tblQuadranteUsuarioCadastro;
		this.tblQuadranteDataAlteracao = tblQuadranteDataAlteracao;
	}

	public Tblquadrante(String tblQuadranteNome, String tblQuadrantePoints, String tblQuadranteOrdem,
			String tblQuadranteDesabilitar, int tblQuadranteVersao, Date tblQuadranteDataCadastro,
			int tblQuadranteUsuarioCadastro, Date tblQuadranteDataAlteracao, Integer tblQuadranteUsuarioAlteracao) {
		this.tblQuadranteNome = tblQuadranteNome;
		this.tblQuadrantePoints = tblQuadrantePoints;
		this.tblQuadranteOrdem = tblQuadranteOrdem;
		this.tblQuadranteDesabilitar = tblQuadranteDesabilitar;
		this.tblQuadranteVersao = tblQuadranteVersao;
		this.tblQuadranteDataCadastro = tblQuadranteDataCadastro;
		this.tblQuadranteUsuarioCadastro = tblQuadranteUsuarioCadastro;
		this.tblQuadranteDataAlteracao = tblQuadranteDataAlteracao;
		this.tblQuadranteUsuarioAlteracao = tblQuadranteUsuarioAlteracao;
	}

	public Integer getTblQuadranteId() {
		return this.tblQuadranteId;
	}

	public void setTblQuadranteId(Integer tblQuadranteId) {
		this.tblQuadranteId = tblQuadranteId;
	}

	public String getTblQuadranteNome() {
		return this.tblQuadranteNome;
	}

	public void setTblQuadranteNome(String tblQuadranteNome) {
		this.tblQuadranteNome = tblQuadranteNome;
	}

	public String getTblQuadrantePoints() {
		return this.tblQuadrantePoints;
	}

	public void setTblQuadrantePoints(String tblQuadrantePoints) {
		this.tblQuadrantePoints = tblQuadrantePoints;
	}

	public String getTblQuadranteOrdem() {
		return this.tblQuadranteOrdem;
	}

	public void setTblQuadranteOrdem(String tblQuadranteOrdem) {
		this.tblQuadranteOrdem = tblQuadranteOrdem;
	}

	public String getTblQuadranteDesabilitar() {
		return this.tblQuadranteDesabilitar;
	}

	public void setTblQuadranteDesabilitar(String tblQuadranteDesabilitar) {
		this.tblQuadranteDesabilitar = tblQuadranteDesabilitar;
	}

	public int getTblQuadranteVersao() {
		return this.tblQuadranteVersao;
	}

	public void setTblQuadranteVersao(int tblQuadranteVersao) {
		this.tblQuadranteVersao = tblQuadranteVersao;
	}

	public Date getTblQuadranteDataCadastro() {
		return this.tblQuadranteDataCadastro;
	}

	public void setTblQuadranteDataCadastro(Date tblQuadranteDataCadastro) {
		this.tblQuadranteDataCadastro = tblQuadranteDataCadastro;
	}

	public int getTblQuadranteUsuarioCadastro() {
		return this.tblQuadranteUsuarioCadastro;
	}

	public void setTblQuadranteUsuarioCadastro(int tblQuadranteUsuarioCadastro) {
		this.tblQuadranteUsuarioCadastro = tblQuadranteUsuarioCadastro;
	}

	public Date getTblQuadranteDataAlteracao() {
		return this.tblQuadranteDataAlteracao;
	}

	public void setTblQuadranteDataAlteracao(Date tblQuadranteDataAlteracao) {
		this.tblQuadranteDataAlteracao = tblQuadranteDataAlteracao;
	}

	public Integer getTblQuadranteUsuarioAlteracao() {
		return this.tblQuadranteUsuarioAlteracao;
	}

	public void setTblQuadranteUsuarioAlteracao(Integer tblQuadranteUsuarioAlteracao) {
		this.tblQuadranteUsuarioAlteracao = tblQuadranteUsuarioAlteracao;
	}

}
