package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

/**
 * TblusuarioHasTbldepartamento generated by hbm2java
 */
public class TblusuarioHasTbldepartamento implements java.io.Serializable {

	private Integer id;
	private int tblUsuarioTblUsuarioId;
	private int tblDepartamentoTblDepartamentoId;

	public TblusuarioHasTbldepartamento() {
	}

	public TblusuarioHasTbldepartamento(int tblUsuarioTblUsuarioId, int tblDepartamentoTblDepartamentoId) {
		this.tblUsuarioTblUsuarioId = tblUsuarioTblUsuarioId;
		this.tblDepartamentoTblDepartamentoId = tblDepartamentoTblDepartamentoId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getTblUsuarioTblUsuarioId() {
		return this.tblUsuarioTblUsuarioId;
	}

	public void setTblUsuarioTblUsuarioId(int tblUsuarioTblUsuarioId) {
		this.tblUsuarioTblUsuarioId = tblUsuarioTblUsuarioId;
	}

	public int getTblDepartamentoTblDepartamentoId() {
		return this.tblDepartamentoTblDepartamentoId;
	}

	public void setTblDepartamentoTblDepartamentoId(int tblDepartamentoTblDepartamentoId) {
		this.tblDepartamentoTblDepartamentoId = tblDepartamentoTblDepartamentoId;
	}

}
