package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * Tblusuario generated by hbm2java
 */
public class Tblusuario implements java.io.Serializable {

	private Integer tblUsuarioId;
	private String tblUsuarioNome;
	private String tblUsuarioEmail;
	private String tblUsuarioTelefone;
	private String tblUsuarioSenha;
	private Float tblUsuarioSalario;
	private String tblUsuarioCargo;
	private byte[] tblUsuarioFoto;
	private Integer tblUsuarioIdGerenteTblUsuario;
	private Integer tblUsuarioIdCargoTblCargo;
	private String tblUsuarioObservacoes;
	private String tblUsuarioSexo;
	private String tblUsuarioDias;
	private String tblUsuarioRaca;
	private int tblUsuarioVersao;
	private Date tblUsuarioDataCadastro;
	private Integer tblUsuarioUsuarioCadastro;
	private Date tblUsuarioDataAlteracao;
	private Integer tblUsuarioUsuarioAlteracao;

	public Tblusuario() {
	}

	public Tblusuario(int tblUsuarioVersao, Date tblUsuarioDataCadastro, Date tblUsuarioDataAlteracao) {
		this.tblUsuarioVersao = tblUsuarioVersao;
		this.tblUsuarioDataCadastro = tblUsuarioDataCadastro;
		this.tblUsuarioDataAlteracao = tblUsuarioDataAlteracao;
	}

	public Tblusuario(String tblUsuarioNome, String tblUsuarioEmail, String tblUsuarioTelefone, String tblUsuarioSenha,
			Float tblUsuarioSalario, String tblUsuarioCargo, byte[] tblUsuarioFoto,
			Integer tblUsuarioIdGerenteTblUsuario, Integer tblUsuarioIdCargoTblCargo, String tblUsuarioObservacoes,
			String tblUsuarioSexo, String tblUsuarioDias, String tblUsuarioRaca, int tblUsuarioVersao,
			Date tblUsuarioDataCadastro, Integer tblUsuarioUsuarioCadastro, Date tblUsuarioDataAlteracao,
			Integer tblUsuarioUsuarioAlteracao) {
		this.tblUsuarioNome = tblUsuarioNome;
		this.tblUsuarioEmail = tblUsuarioEmail;
		this.tblUsuarioTelefone = tblUsuarioTelefone;
		this.tblUsuarioSenha = tblUsuarioSenha;
		this.tblUsuarioSalario = tblUsuarioSalario;
		this.tblUsuarioCargo = tblUsuarioCargo;
		this.tblUsuarioFoto = tblUsuarioFoto;
		this.tblUsuarioIdGerenteTblUsuario = tblUsuarioIdGerenteTblUsuario;
		this.tblUsuarioIdCargoTblCargo = tblUsuarioIdCargoTblCargo;
		this.tblUsuarioObservacoes = tblUsuarioObservacoes;
		this.tblUsuarioSexo = tblUsuarioSexo;
		this.tblUsuarioDias = tblUsuarioDias;
		this.tblUsuarioRaca = tblUsuarioRaca;
		this.tblUsuarioVersao = tblUsuarioVersao;
		this.tblUsuarioDataCadastro = tblUsuarioDataCadastro;
		this.tblUsuarioUsuarioCadastro = tblUsuarioUsuarioCadastro;
		this.tblUsuarioDataAlteracao = tblUsuarioDataAlteracao;
		this.tblUsuarioUsuarioAlteracao = tblUsuarioUsuarioAlteracao;
	}

	public Integer getTblUsuarioId() {
		return this.tblUsuarioId;
	}

	public void setTblUsuarioId(Integer tblUsuarioId) {
		this.tblUsuarioId = tblUsuarioId;
	}

	public String getTblUsuarioNome() {
		return this.tblUsuarioNome;
	}

	public void setTblUsuarioNome(String tblUsuarioNome) {
		this.tblUsuarioNome = tblUsuarioNome;
	}

	public String getTblUsuarioEmail() {
		return this.tblUsuarioEmail;
	}

	public void setTblUsuarioEmail(String tblUsuarioEmail) {
		this.tblUsuarioEmail = tblUsuarioEmail;
	}

	public String getTblUsuarioTelefone() {
		return this.tblUsuarioTelefone;
	}

	public void setTblUsuarioTelefone(String tblUsuarioTelefone) {
		this.tblUsuarioTelefone = tblUsuarioTelefone;
	}

	public String getTblUsuarioSenha() {
		return this.tblUsuarioSenha;
	}

	public void setTblUsuarioSenha(String tblUsuarioSenha) {
		this.tblUsuarioSenha = tblUsuarioSenha;
	}

	public Float getTblUsuarioSalario() {
		return this.tblUsuarioSalario;
	}

	public void setTblUsuarioSalario(Float tblUsuarioSalario) {
		this.tblUsuarioSalario = tblUsuarioSalario;
	}

	public String getTblUsuarioCargo() {
		return this.tblUsuarioCargo;
	}

	public void setTblUsuarioCargo(String tblUsuarioCargo) {
		this.tblUsuarioCargo = tblUsuarioCargo;
	}

	public byte[] getTblUsuarioFoto() {
		return this.tblUsuarioFoto;
	}

	public void setTblUsuarioFoto(byte[] tblUsuarioFoto) {
		this.tblUsuarioFoto = tblUsuarioFoto;
	}

	public Integer getTblUsuarioIdGerenteTblUsuario() {
		return this.tblUsuarioIdGerenteTblUsuario;
	}

	public void setTblUsuarioIdGerenteTblUsuario(Integer tblUsuarioIdGerenteTblUsuario) {
		this.tblUsuarioIdGerenteTblUsuario = tblUsuarioIdGerenteTblUsuario;
	}

	public Integer getTblUsuarioIdCargoTblCargo() {
		return this.tblUsuarioIdCargoTblCargo;
	}

	public void setTblUsuarioIdCargoTblCargo(Integer tblUsuarioIdCargoTblCargo) {
		this.tblUsuarioIdCargoTblCargo = tblUsuarioIdCargoTblCargo;
	}

	public String getTblUsuarioObservacoes() {
		return this.tblUsuarioObservacoes;
	}

	public void setTblUsuarioObservacoes(String tblUsuarioObservacoes) {
		this.tblUsuarioObservacoes = tblUsuarioObservacoes;
	}

	public String getTblUsuarioSexo() {
		return this.tblUsuarioSexo;
	}

	public void setTblUsuarioSexo(String tblUsuarioSexo) {
		this.tblUsuarioSexo = tblUsuarioSexo;
	}

	public String getTblUsuarioDias() {
		return this.tblUsuarioDias;
	}

	public void setTblUsuarioDias(String tblUsuarioDias) {
		this.tblUsuarioDias = tblUsuarioDias;
	}

	public String getTblUsuarioRaca() {
		return this.tblUsuarioRaca;
	}

	public void setTblUsuarioRaca(String tblUsuarioRaca) {
		this.tblUsuarioRaca = tblUsuarioRaca;
	}

	public int getTblUsuarioVersao() {
		return this.tblUsuarioVersao;
	}

	public void setTblUsuarioVersao(int tblUsuarioVersao) {
		this.tblUsuarioVersao = tblUsuarioVersao;
	}

	public Date getTblUsuarioDataCadastro() {
		return this.tblUsuarioDataCadastro;
	}

	public void setTblUsuarioDataCadastro(Date tblUsuarioDataCadastro) {
		this.tblUsuarioDataCadastro = tblUsuarioDataCadastro;
	}

	public Integer getTblUsuarioUsuarioCadastro() {
		return this.tblUsuarioUsuarioCadastro;
	}

	public void setTblUsuarioUsuarioCadastro(Integer tblUsuarioUsuarioCadastro) {
		this.tblUsuarioUsuarioCadastro = tblUsuarioUsuarioCadastro;
	}

	public Date getTblUsuarioDataAlteracao() {
		return this.tblUsuarioDataAlteracao;
	}

	public void setTblUsuarioDataAlteracao(Date tblUsuarioDataAlteracao) {
		this.tblUsuarioDataAlteracao = tblUsuarioDataAlteracao;
	}

	public Integer getTblUsuarioUsuarioAlteracao() {
		return this.tblUsuarioUsuarioAlteracao;
	}

	public void setTblUsuarioUsuarioAlteracao(Integer tblUsuarioUsuarioAlteracao) {
		this.tblUsuarioUsuarioAlteracao = tblUsuarioUsuarioAlteracao;
	}

}
