package org.marcelot;
// Generated 15/09/2020 18:55:45 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private Date created;
	private Date modified;

	public Users() {
	}

	public Users(String email, String password) {
		this.email = email;
		this.password = password;
	}

	public Users(String email, String password, Date created, Date modified) {
		this.email = email;
		this.password = password;
		this.created = created;
		this.modified = modified;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

}
